export const FETCH_POST_LOGIN_REQUEST = 'FETCH_POST_LOGIN_REQUEST';
export const FETCH_POST_LOGIN_SUCCESS = 'FETCH_POST_LOGIN_SUCCESS';
export const FETCH_POST_LOGIN_ERROR = 'FETCH_POST_LOGIN_ERROR';

export const FETCH_POST_SIGNUP_REQUEST = 'FETCH_POST_SIGNUP_REQUEST';
export const FETCH_POST_SIGNUP_SUCCESS = 'FETCH_POST_SIGNUP_SUCCESS';
export const FETCH_POST_SIGNUP_ERROR = 'FETCH_POST_SIGNUP_ERROR';

export const FETCH_POST_OTP_REQUEST = 'FETCH_POST_OTP_REQUEST';
export const FETCH_POST_OTP_SUCCESS = 'FETCH_POST_OTP_SUCCESS';
export const FETCH_FORGOT_OTP_SUCCESS = 'FETCH_FORGOT_OTP_SUCCESS';
export const FETCH_POST_OTP_ERROR = 'FETCH_POST_OTP_ERROR';

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const CHECK_TYPE_LOGIN = 'CHECK_TYPE_LOGIN';
export const LOG_OUT = 'LOG_OUT';
export const CHECK_VERIFY = 'CHECK_VERIFY';

export const PROFILE_EPL_REQUEST = 'PROFILE_EPL_REQUEST';
export const PROFILE_EPL_SUCCESS = 'PROFILE_EPL_SUCCESS';
export const PROFILE_EPL_ERROR = 'PROFILE_EPL_ERROR';

export const PROFILE_UPDATE_EPL_REQUEST = 'PROFILE_UPDATE_EPL_REQUEST';
export const PROFILE_UPDATE_EPL_SUCCESS = 'PROFILE_UPDATE_EPL__SUCCESS';
export const PROFILE_UPDATE_EPL__ERROR = 'PROFILE_UPDATE_EPL__ERROR';

export const LOGO_REQUEST = 'LOGO_REQUEST';
export const LOGO_SUCCESS = 'LOGO_SUCCESS';
export const LOGO_ERROR = 'LOGO_ERROR';

export const FETCH_POST_ADD_JOB_REQUEST = 'FETCH_POST_ADD_JOB_REQUEST';
export const FETCH_POST_ADD_JOB_SUCCESS = 'FETCH_POST_ADD_JOB_SUCCESS';
export const FETCH_POST_ADD_JOB_ERROR = 'FETCH_POST_ADD_JOB_ERROR';

export const FETCH_GET_JOB_REQUEST = 'FETCH_GET_JOB_REQUEST';
export const FETCH_GET_JOB_SUCCESS = 'FETCH_GET_JOB_SUCCESS';
export const FETCH_GET_JOB_ERROR = 'FETCH_GET_JOB_ERROR';

export const FETCH_POST_UPDATE_JOB_REQUEST = 'FETCH_POST_UPDATE_JOB_REQUEST';
export const FETCH_POST_UPDATE_JOB_SUCCESS = 'FETCH_POST_UPDATE_JOB_SUCCESS';
export const FETCH_POST_UPDATE_JOB_ERROR = 'FETCH_POST_UPDATE_JOB_ERROR';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_SUCCESS';
