export const FETCH_POST_LOGIN_REQUEST = 'FETCH_POST_LOGIN_REQUEST';
export const FETCH_POST_LOGIN_SUCCESS = 'FETCH_POST_LOGIN_SUCCESS';
export const FETCH_POST_LOGIN_ERROR = 'FETCH_POST_LOGIN_ERROR';
